### ISSUE TITLE
Bot Status

### ISSUE THREAD

**Issue by ghost** [OtterDevelopment/BeemoHelper#3]
Beemo helper is down.
![obraz](https://user-images.githubusercontent.com/116445311/211217326-1e378981-d697-471f-be07-bb825812f7c4.png)
![obraz](https://user-images.githubusercontent.com/116445311/211217331-a7fc6109-ee02-45a0-9404-a9f9d32bb18c.png)

**Comment by PaxGriefs** [comment]
Its still offline why close the ticket?

**Comment by xPolar** [comment]
This issue was originally resolved, however another completely unrelated issue has popped up causing me to indefinitely shut down the bot until I can rewrite it.
